apiVersion: v1
data:
  mooncake_config.json: |
    {
      "mode": "embedded",
      "metadata_server": "P2PHANDSHAKE",
      "master_server_address": "mooncake-master.default.svc.cluster.local:50051",
      "protocol": "rdma",
      "device_name": "",
      "global_segment_size": "96gb",
      "local_buffer_size": "4gb"
    }
kind: ConfigMap
metadata:
  name: mooncake-config
